### ISSUE TITLE
Single product page changes

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/dlm-theme#1]
- [x] sidebar mutat in dreapta
- [ ] variatiile de produs, trebuie sa afiseze nr. de site-uri pt. care corespunde licenta (acum sunt intr-un dropdown)
- [x] eliminat bara de "buy now" de la sfarsitul articolului
- [x] eliminat link-ul catre changelog
- [ ] zona de cumparat a produsului trebuie sa fie "sticky", pe masura ce scrollezi
- [x] numele developer-ului trebuie eliminat
- [ ] sub zona de header, trebuie afisat un CTA cu "Included in extended pass" (vezi linkul de la EDD de mai jos)
- [ ] zona de titlu, pe centru, ca la EDD 
![image](https://user-images.githubusercontent.com/7841556/113564216-a31b0700-9611-11eb-9c54-1c085bebd5a7.png)

**Comment by cristianraiber** [comment]
O pagina care poate fi folosita drept exemplu: https://easydigitaldownloads.com/downloads/stripe-gateway/

**Comment by giucu91** [comment]
La zona de titlu sa punem product description sub titlu ca sa fie ca la EDD. De asemenea te rog sa copii si spacingul de la EDD.

![image](https://user-images.githubusercontent.com/7580330/116966771-98f43300-acb9-11eb-96d9-7d9a2d614401.png)

**Comment by cristinnaiulia** [comment]
@cristianraiber avem nevoie de breadcrumps pe pagina de produs?

**Comment by cristianraiber** [comment]
> @cristianraiber avem nevoie de breadcrumps pe pagina de produs?

Nup
